# Generated by Django 4.2.3 on 2023-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_countries',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_country',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
